name: tech_feed
description: Tech feed app with AdMob ads
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.1.0
  shared_preferences: ^2.2.3
flutter:
  uses-material-design: true
